//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryServiceWebDBServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountReference
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> CentreId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Person Person { get; set; }
        public virtual DistributionCentre DistributionCentre { get; set; }
    }
}
