//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryServiceWebDBServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.NumberOfPackages = 1;
            this.UserPackages = new HashSet<UserPackage>();
            this.Records = new HashSet<Record>();
        }
    
        public int Id { get; set; }
        public int PersonIdFrom { get; set; }
        public int PersonIdTo { get; set; }
        public Nullable<int> TariffId { get; set; }
//  [Required(ErrorMessage = "Это поле обязательно для заполнения.")]
        public string Description { get; set; }
  //      [Required(ErrorMessage = "Это поле обязательно для заполнения.")]
        public Nullable<double> Weight { get; set; }
    //    [Required(ErrorMessage = "Это поле обязательно для заполнения.")]
        public Nullable<double> Length { get; set; }
      //  [Required(ErrorMessage = "Это поле обязательно для заполнения.")]
        public Nullable<double> Width { get; set; }
      //  [Required(ErrorMessage = "Это поле обязательно для заполнения.")]
        public Nullable<double> Height { get; set; }
      //  [Required(ErrorMessage = "Это поле обязательно для заполнения.")]
        public int NumberOfPackages { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> DeclaredValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPackage> UserPackages { get; set; }
        public virtual Person PersonFrom { get; set; }
        public virtual Person PersonTo { get; set; }
        public virtual Tariff Tariff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records { get; set; }
    }
}
